# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "documento", :force => true do |t|
    t.column "archivo",        :binary,                :default => "", :null => false
    t.column "metadata",       :text,                  :default => "", :null => false
    t.column "peso_numerico1", :integer, :limit => 10, :default => 0,  :null => false
    t.column "peso_numerico2", :integer, :limit => 10, :default => 0,  :null => false
    t.column "peso_numerico3", :integer, :limit => 10, :default => 0,  :null => false
    t.column "peso_numerico4", :integer, :limit => 10, :default => 0,  :null => false
    t.column "procesado",      :integer, :limit => 10, :default => 0,  :null => false
  end

  create_table "documento_palabra", :id => false, :force => true do |t|
    t.column "documento_id",                 :integer, :limit => 10,                :null => false
    t.column "palabra_id",                   :integer, :limit => 10, :default => 0, :null => false
    t.column "frecuencia_en_contenido",      :integer, :limit => 10, :default => 0, :null => false
    t.column "frecuencia_en_titulo",         :integer, :limit => 10, :default => 0, :null => false
    t.column "frecuencia_en_palabras_clave", :integer, :limit => 10, :default => 0, :null => false
    t.column "frecuencia_en_resumen",        :integer, :limit => 10, :default => 0, :null => false
    t.column "frecuencia_en_autor",          :integer, :limit => 10, :default => 0, :null => false
  end

  add_index "documento_palabra", ["documento_id"], :name => "documento_has_palabra_FKIndex1"
  add_index "documento_palabra", ["palabra_id"], :name => "documento_has_palabra_FKIndex2"

  create_table "palabra", :force => true do |t|
    t.column "texto", :string, :limit => 45, :default => "", :null => false
  end

  add_index "palabra", ["texto"], :name => "indice_unico_texto", :unique => true

end
